debug: false
messagefolders:
  - messages
custom_messages:
  服务器信息:
    trigger: "服务器信息"
    #需要启用的群列表,无则全局启用
    groups:
      - "0000000"
    responses:
      - "在线: %server_online% 玩家"
      - "[image] 服务器信息图片"
  我的信息:
    #有则未绑定用户的玩家发送此消息,无则忽略是否绑定
    unbind_messages:
      - "您还没有绑定游戏ID 请输入/bd 名字进行绑定"
    trigger: "我的信息"
    responses:
      - "[image] 玩家信息图片"
  执行命令:
    trigger: "玩家列表"
    responses:
      - "[command] list"
  正则匹配:
    trigger: "[regex] .*氪金.*"
    responses:
      - "服务器直接输入/amc 金额 即可氪金"
  加群欢迎:
    trigger: "[join]"
    responses:
      - "[CQ:at,qq={qq}]欢迎加入本服务器,目前在线%server_online%玩家"
  特殊消息:
    trigger: '音乐'
    responses:
      - '[CQ:music,type=custom,url=https://y.music.163.com/m/song?id=526203483&uct=tQHIc%2BP321sz%2B%2FDMnTZfgg%3D%3D&app_version=8.2.61,audio=http://music.163.com/song/media/outer/url?id=1446791775,image=https://p1.music.126.net/dIp4lnixJvVQBEK8lmLxKg==/109951164973024272.jpg,content=拼音师,title=老八秘制小汉堡2.0]'
custom_images:
  在线人数:
    source: "在线人数.png"
    texts:
      在线人数:
        text: "%server_online%"
        x: 290
        z: 270
        font: 站酷高端黑体
        #字体大小
        size: 120
        #字体样式 0 =普通 #1=加粗 #2=斜体 #3=加粗斜体
        style: 0
  玩家信息图片:
    source: "个人信息.png"
    texts:
      玩家名称:
        text: "&#3380ff%player_name%"
        x: 245
        z: 280
        font: 站酷高端黑体
        #字体大小
        size: 53
        #字体样式 0 =普通 #1=加粗 #2=斜体 #3=加粗斜体
        style: 0
      玩家金币:
        text: "&#F2994A%vault_eco_balance%&#7F8A9B枚"
        x: 275
        z: 390
        font: 站酷高端黑体
        #字体大小
        size: 53
        #字体样式 0 =普通 #1=加粗 #2=斜体 #3=加粗斜体
        style: 0
      在线状态:
        text: "%offlinePapi_playerIsOnline%"
        x: 276
        z: 500
        font: 旁门正道标题体
        #字体大小
        size: 55
        #字体样式 0 =普通 #1=加粗 #2=斜体 #3=加粗斜体
        style: 0
